### ISSUE TITLE
Data overlapping on HT dashboard

### ISSUE THREAD

**Issue by sarthak77** [hypertrace/hypertrace-ui#1298]
Data and headings are overlapping on HT dashboard. 

Preview : 

<img width="724" alt="Screenshot 2021-12-01 at 11 32 40 AM" src="https://user-images.githubusercontent.com/32260832/144253823-a80ac907-5a90-4f88-a7cb-e94566c02e2e.png">

**Comment by jaywalker21** [comment]
This is more of a change in the UX of the screen. Attaching the screenshot of how it used to look like before for reference.

![image](https://user-images.githubusercontent.com/56739130/147495317-4bee4882-a775-4ed6-81c6-618a6659d279.png)

Can someone from the UX team refer this and get back if this is actually needed?

IMO, the previous UX was much more legible.

**Comment by aayushtrace** [comment]
This is an implementation bug. we should revert it to how it was before. @jaywalker21

**Comment by aaron-steinfeld** [comment]
@palbizu do you mind taking this up? I believe this is caused by a change to titled content that looks to be unintended (the regular and grayed out styles for footer are applied to the title element, but the rules got moved up a level). Since this is the only place we use a footer title position, I believe we can safely fix this.

https://github.com/hypertrace/hypertrace-ui/pull/1235/files#diff-93f6302264deca448ff721a7b223fda76ead07f0bfd9e4866c397d2c34d83a99R71-R77
